
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Feb 16 15:39:15 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 16;
  public static final int CONST = 31;
  public static final int GE = 4;
  public static final int LPAREN = 15;
  public static final int SEMI = 32;
  public static final int MINUS = 13;
  public static final int CHARACTER = 39;
  public static final int RPAREN = 5;
  public static final int LT = 9;
  public static final int BOOL = 37;
  public static final int COMMA = 6;
  public static final int INC = 24;
  public static final int DIV = 12;
  public static final int PLUS = 3;
  public static final int ASSIGN = 33;
  public static final int DOT = 10;
  public static final int LE = 25;
  public static final int EOF = 0;
  public static final int RETURN = 27;
  public static final int RBRACKET = 17;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int MUL = 20;
  public static final int NUMBER = 36;
  public static final int MOD = 18;
  public static final int IDENT = 38;
  public static final int VOID = 14;
  public static final int EQ = 28;
  public static final int COLON = 2;
  public static final int LBRACE = 34;
  public static final int ENUM = 19;
  public static final int READ = 23;
  public static final int RBRACE = 35;
  public static final int PROG = 30;
  public static final int NE = 7;
  public static final int QUESTION = 21;
  public static final int DEC = 29;
  public static final int GT = 22;
  public static final int PRINT = 26;
  public static final int LENGTH = 11;
}

